// Chick-fil-B Brand Colors (from web Tailwind config)
export default {
  primary: '#ba0026',
  primaryContainer: '#e51636',
  onPrimary: '#ffffff',
  surface: '#f9f9f9',
  surfaceContainer: '#eeeeee',
  surfaceContainerLow: '#f3f3f3',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerHigh: '#e8e8e8',
  surfaceContainerHighest: '#e2e2e2',
  surfaceVariant: '#e2e2e2',
  onSurface: '#1a1c1c',
  secondary: '#5f5e5e',
  tertiary: '#785500',
  tertiaryContainer: '#986c00',
  onTertiaryContainer: '#fffbf9',
  tertiaryFixed: '#ffdea8',
  onTertiaryFixed: '#271900',
  error: '#ba1a1a',
  inverseSurface: '#2f3131',
  inverseOnSurface: '#f1f1f1',
  outline: '#926e6d',
  tabIconDefault: '#5f5e5e',
  tabIconSelected: '#ba0026',
};
